"""Adds owner to card

Revision ID: 1b3f164bc45a
Revises: d5865f6e2f05
Create Date: 2024-12-23 11:12:56.640753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b3f164bc45a'
down_revision = 'd5865f6e2f05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.String(length=25), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
